### ISSUE TITLE
MethodError: no method matching Float64(::Yota.TReal)

### ISSUE THREAD

**Issue by baggepinnen** [dfdx/Yota.jl#9] opened 2018-08-18 14:35 UTC
I was playing around with this package a little and encountered this (bug?)
```julia
using Yota

inp    = randn(3)             # Input
v      = randn(3)             # Vector
H      = randn(3,3); H = H+H' # Hessian
f(inp) = 0.5*inp'*(H*inp)     # i'H*i function to take hessian of
x      = inp
fp(x)  = grad(f,x)

julia> fp(x)
ERROR: MethodError: no method matching Float64(::Yota.TReal)
Closest candidates are:
  Float64(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:173
  Float64(::T<:Number) where T<:Number at boot.jl:725
  Float64(::Int8) at float.jl:60
  ...
Stacktrace:
 [1] Float64(::Yota.TReal) at ./deprecated.jl:468
 [2] convert at ./number.jl:7 [inlined]
 [3] setindex! at ./array.jl:769 [inlined]
 [4] generic_matvecmul!(::Array{Float64,1}, ::Char, ::Array{Float64,2}, ::Yota.TArray{Float64,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/matmul.jl:539
 [5] mul! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/matmul.jl:75 [inlined]
 [6] *(::Array{Float64,2}, ::Yota.TArray{Float64,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/matmul.jl:50
 [7] f(::Yota.TArray{Float64,1}) at ./REPL[44]:1
 [8] _grad(::Function, ::Array{Float64,1}) at /home/fredrikb/.julia/packages/Yota/bpWWg/src/grad.jl:129
 [9] #grad#36(::Bool, ::Function, ::Function, ::Array{Float64,1}) at /home/fredrikb/.julia/packages/Yota/bpWWg/src/grad.jl:171
 [10] grad at /home/fredrikb/.julia/packages/Yota/bpWWg/src/grad.jl:163 [inlined]
 [11] fp(::Array{Float64,1}) at ./REPL[49]:1
 [12] top-level scope at none:0
```

**Comment by dfdx** [comment] 2018-08-18 18:50
Try this: 

```
inp    = randn(3)             # Input
v      = randn(3)             # Vector
H      = randn(3,3); H = H+H' # Hessian

f(inp,H) = 0.5*transpose(inp)*(H*inp)     # i'H*i function to take hessian of
x      = inp
fp(x)  = grad(f,x,H)
```
All in all, you came too early - Yota doesn't have a registered version and isn't intended for general use just yet (the package is less than 1 month old after all). In practice this means that I've only tested it for a limited case of ML models which don't include: 

 * global variables like `H`
 * `Adjoint` matrices created via `inp'` (although `transpose` works)

Don't hesitate to report more issues though! I'm currently working on integration with CuArrays and performance optimizations, and expect to get to such issues shortly after that.

**Comment by baggepinnen** [comment] 2018-08-20 10:32
Thanks, I tried and your code runs. The following does however not, and returns the same error as before.
```julia
function f(x)
  H = [ -0.466054  -1.67757   0.227333
 -1.67757   -0.7407    1.90789
  0.227333   1.90789  -1.10871]
  transpose(x)*(H*x)      # i'H*i function to take hessian of
end
fp(x)  = grad(f,x)
fp(x)
```

I realize this package is not ready for consumption yet. I got interested because I noticed it could handle a simple version of one of my exotic use cases with nested differentiation, which almost no other AD-library handles:

```julia
using Yota, ForwardDiff

f(w,x) = w*x
# Return closure over x
function loss(w,x)
    ∇xf(x) = ForwardDiff.jacobian(x->f(w,x), x) # This closes over latest w
    w -> sum(abs2.(w)) + norm(∇xf(x)) # Loss function contains nested differentiation of the model with respect to the input
end

w = randn(3,3)
x = randn(3)
l = loss(w,x)
val,g = Yota.grad(l,w) # Only Yota and ReverseDiff handles this
```

ReverseDiff is very slow and sometimes runs out of memory while compiling the tape for my use case, so I'm looking for alternatives.

**Comment by dfdx** [comment] 2018-08-20 22:22
Wow, I've never expected it to work with ForwardDiff, so Yota seems to work better than I expected :D 

Anyway, I'm now (more or less) done with CuArrays and can pay more attention to this issue. A quick test shows that the problem is in multiplication of constant `H::Array` with tracked `x::TArray`, and this multiplication just isn't implemented. If it's the only issue, I should fix it in a day or two.

**Comment by dfdx** [comment] 2018-08-22 21:56
Please, check out latest master, it should fix the issue with constant Hessian matrix. Adjoint matrix (`x'`) on its way.

**Comment by baggepinnen** [comment] 2018-08-23 10:59
Indeed, now it does work with the constant Hessian, thanks!

**Comment by dfdx** [comment] 2018-08-25 23:42
Now all the examples in this issue run on latest master, so I'm going to close it. Please, feel free to reopen or submit a new issue if you encounter other problems.

**Closed as completed by dfdx** 2018-08-25 23:42 UTC
